### ISSUE TITLE
ecs_service - Support force_new_deployment without having to specify a task definition

### ISSUE THREAD

**Issue by giom-l** [ansible-collections/community.aws#1106]
### Summary

Sometimes, it can be helpful to just restart all tasks from a service, without having to deal with all tasks definitions (since they do not need to change).

For that purpose, the aws cli offers the following possibility : 
```
aws ecs update-service --cluster cluster_name --service service_name --force-new-deployment
```
This is particularly interesting when we want some external files to be taken (but the task definition itself does not need any change).

We can note that boto3 already support this option (at least since `v1.14.2` i'm working with) : 
```python
import boto3
client = boto3.client('ecs')
client.update_service(cluster='cluster_name', service='service_name', forceNewDeployment=True)
```

However, the `ecs_service` module can not do that since when we specify `state: present`, we get the following error 
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: task_definition"}
```

### Issue Type

Feature Idea

### Component Name

ecs_service

### Additional Information

An rough idea would be to add an additional parameter (like `preserve_tasks_definitions`) which would, when true, avoid the check about the presence of `task_definition`.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by giom-l** [comment]
I didn't mention it, but it is indeed workaroundable, but requires some more tasks  to retrieve informations about loadBalancers & taskdefinition.

```ansible
- name: Retrieve service details
  community.aws.ecs_service_info:
    cluster: "{{ cluster_name }}"
    service: "{{ service_name }}"
    details: true
  register: service_details

- name: Reload ECS service
  community.aws.ecs_service:
    cluster: "{{ cluster_name }}"
    name: "{{ service_name }}"
    state: present
    force_new_deployment: yes
    load_balancers: "{{ service_details.services | map(attribute='loadBalancers') | first }}"
    task_definition: "{{ service_details.services | map(attribute='taskDefinition') | first }}"
```

The main idea of this feature request it to improve the user experience by not having to deal with data we do not care about at the moment.

**Comment by markuman** [comment]
> We can note that boto3 already support this option (at least since `v1.14.2` i'm working with) :
> 
> ```python
> import boto3
> client = boto3.client('ecs')
> client.update_service(cluster='cluster_name', service='service_name', forceNewDeployment=True)
> ```
> 
> However, the `ecs_service` module can not do that since when we specify `state: present`, we get the following error
> 
> ```
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: task_definition"}
> ```

So a new boolean parameter `force_new_deployment` must be introduced.  
When it got no default value, it can be mutually exclusive with the `state`  parameter.  

@giom-l do you have some time to implement this new feature?

**Comment by giom-l** [comment]
Hi,

Not this week but I can take a look at it the next one, sure.
Just to be sure about what to do : you write about a new Boolean parameter,
but there is already an existing one with this name :
https://docs.ansible.com/ansible/latest/collections/community/aws/ecs_service_module.html#parameter-force_new_deployment

It is just the behaviour of this one that should be changed, right ?
(NB : I haven't the whole code in front of me right now so I may have
missed something)

Le dim. 1 mai 2022 à 07:35, Markus Bergholz ***@***.***> a
écrit :

**Comment by markuman** [comment]
Ah sorry. I thought the entire parameter was missing.  
So yes, imo the internally logic must just be fixed, so that  `force_new_deployment: yes` works also on existing service without the need to specify the taskdefinition.
