### ISSUE TITLE
SSM connection doesn't use regional S3 endpoint

### ISSUE THREAD

**Issue by davidgiga1993** [ansible-collections/community.aws#1190]
### Summary

When using `ansible_connection: aws_ssm` the url used to download data from a bucket is always `*.s3.amazonaws.com` regardless of the region specified in `ansible_aws_ssm_region`.

This causes issues since in restricted environments the EC2 instance has to use the S3 gateway endpoint which is only available using the region specific url, for example `*.s3.eu-central-1.amazonaws.com`

### Issue Type

Bug Report

### Component Name

s3

### Ansible Version

```console (paste below)
$ ansible --version
ansible [core 2.12.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ssm-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/ssm-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
Name: boto3
Version: 1.24.0
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: s3transfer, botocore, jmespath
Required-by:
---
Name: botocore
Version: 1.27.0
Summary: Low-level, data-driven core of boto 3.
Home-page: https://github.com/boto/botocore
Author: Amazon Web Services
Author-email:
License: Apache License 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: python-dateutil, jmespath, urllib3
Required-by: s3transfer, boto3
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Ubuntu 22

### Steps to Reproduce

```yaml 
ll:
  hosts:
    test:
      ansible_connection: aws_ssm
      ansible_aws_ssm_instance_id: "i-...."

  vars:
    ansible_aws_ssm_bucket_name: my-bucket
    ansible_aws_ssm_region: eu-central-1
```

### Expected Results

Ansible should use the region specific s3 url for download

### Actual Results

```console (paste below)
EXEC curl 'https://my-bucket.s3.amazonaws.com/...
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by bodnarbm** [comment]
Can we reopen this issue? 

The referenced PR in the close action above (#1176) does not seem to resolve this particular issue. That PR was targeting a fix for pulling the region information for the S3 bucket used for SSM file transfers from the bucket metadata itself, but the pre-signed URLs generated for the S3 downloads are still pointing at the global S3 endpoint, and not the region specific one. 

This still creates the issue indicated in #637 (which also needs to be reopened), where newly created S3 buckets returned 307 redirects from the global endpoint to use the regional endpoint instead within the first 24 hours, and then the signature fails as the signature was intended for the global endpoint and not the regional endpoint.

**Comment by simon97k** [comment]
> Can we reopen this issue?
> 
> The referenced PR in the close action above ([#1176](https://github.com/ansible-collections/community.aws/pull/1176)) does not seem to resolve this particular issue. That PR was targeting a fix for pulling the region information for the S3 bucket used for SSM file transfers from the bucket metadata itself, but the pre-signed URLs generated for the S3 downloads are still pointing at the global S3 endpoint, and not the region specific one.
> 
> This still creates the issue indicated in [#637](https://github.com/ansible-collections/community.aws/issues/637) (which also needs to be reopened), where newly created S3 buckets returned 307 redirects from the global endpoint to use the regional endpoint instead within the first 24 hours, and then the signature fails as the signature was intended for the global endpoint and not the regional endpoint.

I can confirm that something with the used S3 endpoints is not working as expected. When this intermediate S3 bucket used for up- and download of the file transfer is hosted in e.g. eu-central-1 or ap-southeast-1 everything works fine, while when this bucket is hosted (with the same settings) in ap-east-1 Ansible returns this:

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (InvalidToken) when calling the GetBucketLocation operation: The provided token is malformed or otherwise invalid.
fatal: [i-XXXXXXXXXXXX]: FAILED! => {"msg": "Unexpected failure during module execution: An error occurred (InvalidToken) when calling the GetBucketLocation operation: The provided token is malformed or otherwise invalid.", "stdout": ""}`


A workaround is quiet easy by setting a environment variable in the playbook options, but it should be built-in if possible:
````yaml
- name: Demo for regional Env Var
  hosts: all
  connection: community.aws.aws_ssm
  environment:
    AWS_STS_REGIONAL_ENDPOINTS: "regional"
````
