### ISSUE TITLE
module links in galaxy now broken

### ISSUE THREAD

**Issue by samccann** [ansible-collections/community.aws#1461]
### Summary

This is a side effect of https://github.com/ansible-collections/community.aws/pull/1436 which replaced the .rst files in the repo with a github-generated docsite.

This caused a few issues:
1 - galaxy readme links are now broken because the readme points to .rst files that were removed from the repo. This is probably fixed as soon as the next `community.aws` release picks up the new readme file.
2 - The new readme file always points to the main branch for docs. This means galaxy would not reflect the release that is on galaxy.  One suggested fix would be to replace the existing link at https://github.com/ansible-collections/community.aws/blame/main/README.md#L38 with a link to devel docs on docs.ansible.com (https://docs.ansible.com/ansible/devel/collections/community/aws/index.html).  Alternately, consider the approach used at https://github.com/ansible-collections/community.hashi_vault/#collection-documentation which points to multiple versions.
3. the docsite in galaxy.yml should be updated as well here - https://github.com/ansible-collections/community.aws/blob/main/galaxy.yml#L13  This one can be the devel docs link as what is latest in galaxy is devel on docs.ansible.com.

### Issue Type

Documentation Report

### Component Name

docs

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by samccann** [comment]
More options from the DaWGs meeting:

the AWS collections also have another option since they use stable branches
in the galaxy.yml for those "not latest" branches, they could point to the docsites built by the GH workflows for those branches
but I don't know how difficult that would be to manage
I don't think they've been published yet, but the workflows are set up to do so
or it could point to the tag docs builds, which will be built when the tag is pushed
etc.

**Comment by tremble** [comment]
> 2 - The new readme file always points to the main branch for docs.

Thanks for the catch (and sorry I went silent in the meeting)

Bah, I could have sworn I caught this one.  Must have only updated it for the workflows.
