### ISSUE TITLE
Add version_description to ec2_launch_template 

### ISSUE THREAD

**Issue by squirrel532** [ansible-collections/community.aws#1762]
### Summary

I found that `ec2_launch_template` does not expose `VersionDescription` from `create_launch_template_version`.

- [create_launch_template_version](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/create_launch_template_version.html)

### Issue Type

Feature Idea

### Component Name

ec2_launch_template

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
@squirrel532 do you have time to contribute this feature?
