### ISSUE TITLE
Add support for transit gateway to transit gateway peering 

### ISSUE THREAD

**Issue by scottmacdonaldclearobject** [ansible-collections/community.aws#1791]
### Summary

I am trying to peer together 2 transit gateways, and there is no module to accomplish this. 

### Issue Type

Feature Idea

### Component Name

tgw_attachment, tgw_peering 

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

**Comment by tremble** [comment]
Closing as a duplicate of #1787
