### ISSUE TITLE
Integration tests need to be updated to avoid unsafe templating

### ISSUE THREAD

**Issue by jillr** [ansible-collections/community.aws#2012]
### Summary

See: https://github.com/ansible/ansible-documentation/pull/866 and  https://github.com/ansible/ansible-documentation/pull/866
Due to a CVE mitigation, there are some assert tasks that may begin failing in CI.  Affected tasks can be identified with https://gist.github.com/sivel/7b012ae2ebf4ab4cb6225379a72cc502

### Issue Type

Bug Report

### Component Name

integration tests

### Ansible Version

```console (paste below)
$ ansible --version

```

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### Steps to Reproduce

```yaml (paste below)

```

### Expected Results

we need to update affected tests to avoid CI failures

### Actual Results

```console (paste below)
 
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
- [ ] tests/integration/targets/redshift/tasks/main.yml:123:13: [assert create success] - result.cluster.identifier == "{{ redshift_cluster_name }}"
- [ ] tests/integration/targets/redshift/tasks/main.yml:146:13: [assert no change gets made to the existing cluster] - result.cluster.identifier == "{{ redshift_cluster_name }}"
- [ ] tests/integration/targets/redshift/tasks/main.yml:169:13: [assert cluster was modified] - result.cluster.identifier == "{{ redshift_cluster_name }}-modified"
- [ ] tests/integration/targets/redshift/tasks/main.yml:237:13: [assert create] - result.cluster.identifier == "{{ redshift_cluster_name }}"
- [ ] tests/integration/targets/redshift/tasks/main.yml:263:13: [assert tags change] - result.cluster.identifier == "{{ redshift_cluster_name }}"
- [ ] tests/integration/targets/redshift/tasks/main.yml:292:13: [assert tags change] - result.cluster.identifier == "{{ redshift_cluster_name }}"
- [ ] tests/integration/targets/redshift/tasks/main.yml:321:13: [assert create] - result.cluster.identifier == "{{ redshift_cluster_name }}"
- [ ] tests/integration/targets/codepipeline/tasks/main.yml:69:13: [assert] - output.pipeline.name == "{{ codepipeline_name  }}"
- [ ] tests/integration/targets/lightsail_snapshot/tasks/main.yml:33:13: [assert] - 'instance_snapshot' in result and result.instance_snapshot.name == '{{ snapshot_name }}'
- [ ] tests/integration/targets/stepfunctions_state_machine/tasks/main.yml:115:13: [assert] - update_check.output == 'State machine would be updated: {{ creation_output.state_machine_arn }}'
- [ ] tests/integration/targets/stepfunctions_state_machine/tasks/main.yml:268:13: [assert] - deletion_check.output == 'State machine would be deleted: {{ creation_output.state_machine_arn }}'
- [ ] tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml:351:9: [health_check_grace_period_seconds sets HealthChecGracePeriodSeconds] - {{ecs_service_creation_hcgp.service.healthCheckGracePeriodSeconds}} == 30
- [ ] tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml:371:9: [check that module returns success] - {{ecs_service_creation_hcgp2.service.healthCheckGracePeriodSeconds}} == 10
- [ ] tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml:456:9: [Check that task definition has been created] - ecs_task_definition_constraints.taskdefinition.placementConstraints[0].type == "{{ ecs_taskdefinition_placement_constraints[0].type }}"
- [ ] tests/integration/targets/ecs_cluster/tasks/20_ecs_service.yml:457:9: [Check that task definition has been created] - ecs_task_definition_constraints.taskdefinition.placementConstraints[0].expression == "{{ ecs_taskdefinition_placement_constraints[0].expression }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:76:13: [cluster tags - tags should be there] - taglist.added_tags.Name == "{{ resource_prefix }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:165:13: [service tag - name tags should be there] - taglist.added_tags.Name == "service-{{ resource_prefix }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:166:13: [service tag - name tags should be there] - taglist.tags.Name == "service-{{ resource_prefix }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:182:13: [service tag - test adding tag twice has no effect] - taglist.tags.Name == "service-{{ resource_prefix }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:218:13: [task_definition tag - name tags should be there] - taglist.added_tags.Name == "task_definition-{{ resource_prefix }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:219:13: [task_definition tag - name tags should be there] - taglist.tags.Name == "task_definition-{{ resource_prefix }}"
- [ ] tests/integration/targets/ecs_tag/tasks/main.yml:235:13: [task_definition tag - test adding tag twice has no effect] - taglist.tags.Name == "task_definition-{{ resource_prefix }}"
- [ ] tests/integration/targets/cloudfront_distribution/tasks/main.yml:171:11: [ensure origin Origin Shield was enabled] - update_origin_origin_shield.origins['items'][0].origin_shield.origin_shield_region == '{{ aws_region }}'
- [ ] tests/integration/targets/sqs_queue/tasks/main.yml:22:13: [Assert SQS queue created] - create_result.region == "{{ aws_region }}"
- [ ] tests/integration/targets/waf_web_acl/tasks/main.yml:564:11: [check failure was sensible] - 'Condition {{ resource_prefix }}_size_condition is in use' in remove_in_use_condition.msg
- [ ] tests/integration/targets/waf_web_acl/tasks/main.yml:677:11: [check failure was sensible] - 'Condition {{ resource_prefix }}_size_condition is in use' in remove_in_use_condition.msg
- [ ] tests/integration/targets/msk_cluster/tasks/test_create.yml:53:9: [validate return values] - msk_cluster.cluster_info.cluster_arn.startswith('arn:aws:kafka:{{ aws_region }}:')
- [ ] tests/integration/targets/ecs_ecr/tasks/main.yml:600:13: [it should use the provided KMS key] - result.repository.encryptionConfiguration.kmsKey == '{{ kms_test_key.key_arn }}'
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:210:13: [assert] - {{ alb_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:211:13: [assert] - {{ nlb_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:212:13: [assert] - {{ idle_target_group.target_group_arn not in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:231:13: [assert] - {{ alb_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:232:13: [assert] - {{ nlb_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:233:13: [assert] - {{ idle_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:245:13: [assert] - {{ alb_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:246:13: [assert] - {{ nlb_target_group.target_group_arn in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/elb_target_info/tasks/main.yml:247:13: [assert] - {{ idle_target_group.target_group_arn not in (target_facts.instance_target_groups | map(attribute='target_group_arn')) }}
- [ ] tests/integration/targets/codecommit_repository/tasks/main.yml:30:11: [assert] - output.repository_metadata.repository_name == '{{ resource_prefix }}_repo'
- [ ] tests/integration/targets/codecommit_repository/tasks/main.yml:42:11: [assert] - output.repository_metadata.repository_name == '{{ resource_prefix }}_repo'
- [ ] tests/integration/targets/codecommit_repository/tasks/main.yml:55:11: [assert] - output.repository_metadata.repository_name == '{{ resource_prefix }}_repo'
- [ ] tests/integration/targets/codecommit_repository/tasks/main.yml:67:11: [assert] - output.repository_metadata.repository_name == '{{ resource_prefix }}_repo'
- [ ] tests/integration/targets/codecommit_repository/tasks/main.yml:107:11: [assert] - output.repository_metadata.repository_name == '{{ resource_prefix }}_repo'
- [ ] tests/integration/targets/codecommit_repository/tasks/main.yml:117:11: [assert] - output.repository_metadata.repository_name == '{{ resource_prefix }}_repo'
- [ ] tests/integration/targets/sns_topic/tasks/main.yml:65:9: [assert success] - sns_topic_info.result["sns_arn"] == "{{ sns_arn }}"
- [ ] tests/integration/targets/sns_topic/tasks/main.yml:82:9: [assert success] - sns_topic_info.result["sns_arn"] == "{{ sns_arn }}"
- [ ] tests/integration/targets/sns_topic/tasks/main.yml:113:9: [assert that FIFO SNS topic creation worked] - sns_fifo_topic.sns_topic.name == '{{ sns_topic_topic_name }}-fifo'
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:526:9: [Create parameter with tags case - Ensure tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_orig['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:581:9: [Update description only case - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_orig['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:636:9: [Add tag to existing parameter case - Ensure tags correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_add_owner['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:707:9: [Change single tag case - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_change_environment['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:778:9: [Delete single tag case - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_delete_version['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:849:9: [Delete single tag w/ spaces case - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_delete_tag_with_space['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:920:9: [Add/delete/change tags case - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_add_delete_change['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:991:9: [Delete all tags case - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_delete_all_tags['{{ item.key }}']
- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1064:9: [Add tag case (purge_tags=false) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == (simple_tags_orig | combine(simple_tags_purge_false_add_owner))['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1073:9: [Add tag case (purge_tags=false) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | combine(simple_tags_purge_false_add_owner) | dict2items }} | length

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1142:9: [Add multiple tags case (purge_tags=false) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == (simple_tags_orig | combine(simple_tags_purge_false_add_multiple))['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1151:9: [Add multiple tags case (purge_tags=false) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | combine(simple_tags_purge_false_add_multiple) | dict2items }} | length

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1220:9: [Change tag case (purge_tags=false) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == (simple_tags_orig | combine(simple_tags_purge_false_change_environment))['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1232:9: [Change tag case (purge_tags=false) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | combine(simple_tags_purge_false_change_environment) | dict2items }} | length

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1301:9: [Change multiple tags (purge_tags=false) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == (simple_tags_orig | combine(simple_tags_purge_false_change_multiple))['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1313:9: [Change multiple tags (purge_tags=false) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | combine(simple_tags_purge_false_change_multiple) | dict2items }} | length

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1382:9: [Add/Change multiple tags (purge_tags=false) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == (simple_tags_orig | combine(simple_tags_purge_false_add_and_change))['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1394:9: [Add/Change multiple tags (purge_tags=false) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | combine(simple_tags_purge_false_add_and_change) | dict2items }} | length

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1463:9: [Empty tags dict (purge_tags=false) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}'] == simple_tags_orig['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1473:9: [Empty tags dict (purge_tags=false) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | dict2items }} | length

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1540:11: [No tags parameter (purge_tags=true) - Ensure expected tags is correct] - result.parameter_metadata.tags['{{ item.key }}']
 == simple_tags_orig['{{ item.key }}']

- [ ] tests/integration/targets/ssm_parameter/tasks/main.yml:1551:11: [No tags parameter (purge_tags=true) - Ensure no missing or additional tags] - result.parameter_metadata.tags | length == {{ simple_tags_orig | dict2items }} | length

- [ ] tests/integration/targets/connection/test_assume.yml:16:9: [assert] - id_cmd.stdout == '{{ user_name }}'
- [ ] tests/integration/targets/msk_cluster-auth/tasks/test_create_auth.yml:65:9: [validate return values] - msk_cluster.cluster_info.cluster_arn.startswith('arn:aws:kafka:{{ aws_region }}:')
- [ ] tests/integration/targets/efs/tasks/main.yml:101:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:110:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:120:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:130:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:140:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:152:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:234:15: [assert] - {{efs_result_assertions}}
- [ ] tests/integration/targets/efs/tasks/main.yml:369:13: [assert] - efs_tag_result.tags.Name is search("{{ efs_name }}-test-tag")
- [ ] tests/integration/targets/efs/tasks/main.yml:467:13: [assert] - efs_tag_result.tags.Name is search("{{ efs_name }}-test-tag")
- [ ] tests/integration/targets/api_gateway_domain/tasks/main.yml:42:13: [assert] - create_result.response.domain.domain_name == "{{ api_gateway_domain_name }}"
- [ ] tests/integration/targets/api_gateway_domain/tasks/main.yml:62:13: [assert] - repeat_result.response.domain_name == "{{ api_gateway_domain_name }}"
- [ ] tests/integration/targets/api_gateway_domain/tasks/main.yml:78:13: [assert] - update_result.response.domain.domain_name == "{{ api_gateway_domain_name }}"
- [ ] tests/integration/targets/autoscaling_scheduled_action/tasks/main.yml:104:13: [Check results - Create basic scheduled_action] - scheduled_action.scheduled_action_name == "{{ resource_prefix }}-test"
- [ ] tests/integration/targets/autoscaling_scheduled_action/tasks/main.yml:158:13: [Check results - Update basic scheduled_action] - scheduled_action.scheduled_action_name == "{{ resource_prefix }}-test"
- [ ] tests/integration/targets/autoscaling_scheduled_action/tasks/main.yml:220:13: [Check results - Create advanced scheduled_action] - advanced_scheduled_action.scheduled_action_name == "{{ resource_prefix }}-test1"
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:58:13: [assert] - "{{ aws_region }}a" in create.elb.zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:59:13: [assert] - "{{ aws_region }}b" in create.elb.zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:77:13: [assert] - "{{ aws_region }}a" in elb.availability_zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:78:13: [assert] - "{{ aws_region }}b" in elb.availability_zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:137:13: [assert] - update_az.elb.zones[0] == "{{ aws_region }}c"
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:147:13: [assert] - "{{ aws_region }}c" in elb.availability_zones[0]
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:173:13: [assert] - "{{ aws_region }}a" in update_az.elb.zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:174:13: [assert] - "{{ aws_region }}b" in update_az.elb.zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:175:13: [assert] - "{{ aws_region }}c" in update_az.elb.zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:185:13: [assert] - "{{ aws_region }}a" in elb.availability_zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:186:13: [assert] - "{{ aws_region }}b" in elb.availability_zones
- [ ] tests/integration/targets/elb_classic_lb_info/tasks/main.yml:187:13: [assert] - "{{ aws_region }}c" in elb.availability_zones
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:28:13: [assert] - pg_1_create_check_mode.placement_group.name == '{{ resource_prefix }}-pg1'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:44:13: [assert] - pg_1_create.placement_group.name == '{{ resource_prefix }}-pg1'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:57:13: [assert] - pg_1_info_result.placement_groups[0].name == '{{ resource_prefix }}-pg1'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:71:13: [assert] - pg_1_create.placement_group.name == '{{ resource_prefix }}-pg1'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:85:13: [assert] - pg_1_create_check_mode_idem.placement_group.name == '{{ resource_prefix }}-pg1'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:100:13: [assert] - pg_2_create_check_mode.placement_group.name == '{{ resource_prefix }}-pg2'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:114:13: [assert] - pg_2_create.placement_group.name == '{{ resource_prefix }}-pg2'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:130:13: [assert] - pg_2_info_result.placement_groups[0].name == '{{ resource_prefix }}-pg2'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:145:13: [assert] - pg_2_create.placement_group.name == '{{ resource_prefix }}-pg2'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:160:13: [assert] - pg_2_create_check_mode_idem.placement_group.name == '{{ resource_prefix }}-pg2'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:176:13: [assert] - pg_3_create_check_mode.placement_group.name == '{{ resource_prefix }}-pg3'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:191:13: [assert] - pg_3_create.placement_group.name == '{{ resource_prefix }}-pg3'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:208:13: [assert] - pg_3_info_result.placement_groups[0].name == '{{ resource_prefix }}-pg3'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:224:13: [assert] - pg_3_create.placement_group.name == '{{ resource_prefix }}-pg3'
- [ ] tests/integration/targets/ec2_placement_group/tasks/main.yml:240:13: [assert] - pg_3_create_check_mode_idem.placement_group.name == '{{ resource_prefix }}-pg3'
- [ ] tests/integration/targets/elb_target/tasks/ec2_target.yml:150:13: [set up testing target group for NLB (type=instance)] - result.target_group_name == "{{ tg_name }}-nlb"
- [ ] tests/integration/targets/elb_target/tasks/ec2_target.yml:217:13: [create a netwok load balancer] - result.vpc_id == '{{ vpc.vpc.id }}'
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:110:11: [assert] - 'An error occurred (ActiveInstanceRefreshNotFound) when calling the CancelInstanceRefresh operation: No in progress or pending Instance Refresh found for Auto Scaling group {{ resource_prefix }}-asg' in result.msg
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:326:13: [assert] - {{ output.instance_refreshes|length }} == 0
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:337:13: [assert] - {{ output.instance_refreshes |length }} == 1
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:357:13: [assert] - {{ output.instance_refreshes|length }} == 7
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:379:13: [assert] - {{ output.instance_refreshes|length }} < 2
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:390:13: [assert] - {{ output.instance_refreshes|length }} == 7
- [ ] tests/integration/targets/autoscaling_instance_refresh/tasks/main.yml:402:13: [assert] - {{ output.instance_refreshes|length }} == 1
- [ ] tests/integration/targets/elb_network_lb/tasks/test_nlb_tags.yml:37:11: [assert] - nlb.tags.created_by == "NLB test {{ resource_prefix }}"
- [ ] tests/integration/targets/elb_network_lb/tasks/test_nlb_tags.yml:49:11: [assert] - nlb.tags.created_by == "NLB test {{ resource_prefix }}"
- [ ] tests/integration/targets/inventory_aws_mq/playbooks/test_populating_inventory.yml:17:13: [assert aws_mq inventory group contains MQ instance created by previous playbook] - groups.aws_mq.0 == '{{ broker_name }}'
- [ ] tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_with_hostvars_prefix_suffix.yml:19:13: [assert the hostvars are defined with prefix and/or suffix] - hostvars[broker_name].{{ vars_prefix }}host_instance_type{{ vars_suffix }} == 'mq.t3.micro'
- [ ] tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_with_hostvars_prefix_suffix.yml:20:13: [assert the hostvars are defined with prefix and/or suffix] - hostvars[broker_name].{{ vars_prefix }}engine_type{{ vars_suffix }} == '{{ engine }}'
- [ ] tests/integration/targets/inventory_aws_mq/playbooks/test_inventory_with_hostvars_prefix_suffix.yml:21:13: [assert the hostvars are defined with prefix and/or suffix] - hostvars[broker_name].{{ vars_prefix }}broker_state{{ vars_suffix }} in ('CREATION_IN_PROGRESS', 'RUNNING')
- [ ] tests/integration/targets/s3_sync/tasks/main.yml:26:13: [assert] - output.name == "{{ test_bucket }}"
- [ ] tests/integration/targets/s3_sync/tasks/main.yml:70:13: [assert] - output.name == "{{ test_bucket_2 }}"
- [ ] tests/integration/targets/s3_sync/tasks/main.yml:116:13: [assert] - output.name == "{{ test_bucket_3 }}"
- [ ] tests/integration/targets/elasticache/tasks/main.yml:63:13: [Assert that task worked] - elasticache_redis.elasticache.name == "{{ elasticache_redis_test_name }}"
- [ ] tests/integration/targets/elasticache/tasks/main.yml:64:13: [Assert that task worked] - elasticache_redis.elasticache.data.CacheSubnetGroupName == "{{ elasticache_subnet_group_name }}"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:49:13: [assert] - result.policy_name == "{{ resource_prefix }}_simplescaling_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:64:13: [assert] - result.policy_name == "{{ resource_prefix }}_simplescaling_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:80:13: [assert] - result.policy_name == "{{ resource_prefix }}_simplescaling_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:97:13: [assert] - result.policy_name == "{{ resource_prefix }}_simplescaling_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:129:13: [assert] - result.policy_name == "{{ resource_prefix }}_stepscaling_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:152:13: [assert] - result.policy_name == "{{ resource_prefix }}_stepscaling_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:192:13: [assert] - result.policy_name == "{{ resource_prefix }}_targettracking_predefined_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:209:13: [assert] - result.policy_name == "{{ resource_prefix }}_targettracking_predefined_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:266:13: [assert] - result.policy_name == "{{ resource_prefix }}_targettracking_custom_policy"
- [ ] tests/integration/targets/autoscaling_policy/tasks/main.yml:288:13: [assert] - result.policy_name == "{{ resource_prefix }}_targettracking_custom_policy"
- [ ] tests/integration/targets/cloudfront_reponse_headers_policy/task/main.yml:27:13: [Assert creation withouth errors and return values] - create_result.response_headers_policy.response_headers_policy_config.name == "{{ resource_prefix }}-my-header-policy"
- [ ] tests/integration/targets/msk_config/tasks/main.yml:56:13: [validate return values] - msk_config.arn.startswith('arn:aws:kafka:{{ aws_region }}:')
- [ ] tests/integration/targets/lightsail/tasks/main.yml:35:13: [assert] - {{ result.instance.networking.ports|length }} == 1
