### ISSUE TITLE
Typo in autoscaling_instance_refresh module in check mode

### ISSUE THREAD

**Issue by gtie** [ansible-collections/community.aws#2019]
### Summary

Typo on line 222 of `autoscaling_instance_refresh.py` , currently reading:
```
                    module.exit_json(chaned=False, msg="In check_mode - No active referesh found, nothing to cancel.")
```
`chaned` needs to get `changed`

### Issue Type

Bug Report

### Component Name

autoscaling_instance_refresh

### Ansible Version

N/A

### Collection Versions

N/A

### AWS SDK versions

N/A

### Configuration

N/A

### Steps to Reproduce

N/A

### Expected Results

N/A

### Actual Results

N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by al-sabri** [comment]
Happy to take as first issue. I just need a bit of help with environment setup. I am running into a couple of issues following https://docs.ansible.com/ansible/latest/community/create_pr_quick_start.html
