### ISSUE TITLE
aws_ssm connection plugin should garbage collect the s3 bucket after the file transfers

### ISSUE THREAD

**Issue by abeluck** [ansible-collections/community.aws#222]
##### SUMMARY

The aws_ssm connection plugin uses an s3 buckets to transfer files to instances. These files remain in the bucket after the play has complete, they are never removed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ssm connection plugin

##### ANSIBLE VERSION
ansible 2.10.1rc2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.7/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
debian 10

##### STEPS TO REPRODUCE

1. use the aws_ssm plugin
2. look at the s3 bucket it used
3. observe that the files are transferred are still there

##### EXPECTED RESULTS

The plugin should garbage collect files after transferring them.

##### ACTUAL RESULTS

Files written remain there forever.

**Comment by jillr** [comment]
Hi @abeluck, thanks for reporting this (and 221).  It looks like you might already be working on a pull request?  We've identified that these are potential security vulnerabilities so if you could please tag me onto any PRs you open I would appreciate it.  I'm also looking at some fixes for the integration tests, in case you've run into any problems running those.
