### ISSUE TITLE
Port rds_subnet_group to boto3

### ISSUE THREAD

**Issue by pm98zz-c** [ansible-collections/community.aws#223]
##### SUMMARY
Use boto3 instead of boto (and remove logic on mandatory arguments on state: absent)

##### ISSUE TYPE
- Chore

##### COMPONENT NAME
rds_subnet_group.py

##### ADDITIONAL INFORMATION
I've only focused on the minimal work to get it working in the same way as it was from a functional point of view. Would probably need some tests and a few additional features (like support for tags), but seems to be working for my use case.

**Comment by tremble** [comment]
Useful trick:  if you add `Fixes: #<issue_number>` to the description of your PR it will automatically close the issue.  I usually drop it either at the start of the description or in the 'Addiitonal Information' section
