### ISSUE TITLE
aws_ec2 inventory plugin filters failed in particular conditions

### ISSUE THREAD

**Issue by kevit** [ansible-collections/community.aws#325]
##### SUMMARY

I realise that EC2 plugin aws_ec2 returns nothing if you define filter based on tag and not all ec2 instances labeled with the filtered tag 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
aws_ec2

##### ANSIBLE VERSION
```
ansible --version
ansible 2.10.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.16 (default, Dec 12 2019, 23:58:22) [GCC 7.3.1 20180712 (Red Hat 7.3.1-6)]
```
##### CONFIGURATION
```
empty
```

##### OS / ENVIRONMENT

AWS Linux

##### STEPS TO REPRODUCE

You should have at least 2 ec2 instances.

1. Define a aws_ec2 config similar to:
```
plugin: aws_ec2
filters: 
 tag:BeEnabled: yes
```
2. Apply tag BeEnabled **only to one instance**
3. run ansible-inventory --graph

##### EXPECTED RESULTS
output contain tagged instances

##### ACTUAL RESULTS
output contains nothing

```
@all:
  |--@aws_ec2:
  |--@ungrouped:
```

**Comment by flowerysong** [comment]
This is not a bug. Unquoted `yes` is a boolean n YAML, and you do not have any instances with the tag `BeEnabled` set to the string `true`.

To force the YAML parser to interpret the value as a string you need to quote it.

```
 tag:BeEnabled: "yes"
```

**Comment by kevit** [comment]
@flowerysong looks like my bad, Quoted "Yes" works fine. Thank you!
