### ISSUE TITLE
how to generate readme (rst) doc for example_module.py ?

### ISSUE THREAD

**Issue by 116davinder** [ansible-collections/community.aws#337]
### SUMMARY
does anyone knows how to generate documentation readme ( rst ) from ansible module.py
is there any ansible utility which generates these readme files.

I have tried `ansible-doc -t module example_module` but doesn't seem to generating same type of output.

**Example**:
**from**: https://github.com/ansible-collections/community.aws/blob/main/plugins/modules/aws_acm_info.py
**to**: https://github.com/ansible-collections/community.aws/blob/main/docs/community.aws.aws_acm_info_module.rst

**Comment by 116davinder** [comment]
@tremble / @markuman , do you guys have any information about this utility/tool ?

**Comment by tremble** [comment]
@116davinder I generally don't generate them: @jillr creates them as a part of the release process (#327).  @jillr or @felixfontein may be able to point you to the relevant documentation.

**Comment by Akasurde** [comment]
@116davinder You can use https://github.com/ansible-network/collection_prep/blob/master/collection_prep/cmd/add_docs.py for generating py -> rst.

```
#  python add_docs.py -p /<PATH>/collections/ansible_collections/community/aws -b main
```

**Comment by felixfontein** [comment]
@tremble I can't, because I'm not really know that tool either. I think it's a tool specific to the Ansible collections team.

**Comment by 116davinder** [comment]
thanks a lot @Akasurde for pointing out, I checked only general and aws repository for this `add_docs.py`
