### ISSUE TITLE
use TagSpecifications to add EC2 instance tags

### ISSUE THREAD

**Issue by mszabo** [ansible-collections/community.aws#462]
##### SUMMARY
The EC2 module currently using `ec2.create_tags` to add tags to the instance. There is a delay between instance creation and adding of the tags.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
amazon.aws.ec2

##### ADDITIONAL INFORMATION

It is not uncommon to have a policy in place within an AWS account that you cannot launch instances without certain tags.
Using the TagSpecifications parameter of `ec2.run_instances` would make sure the tags are applied during the creation of the instance without delay.

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_TagSpecification.html

**Comment by tremble** [comment]
ec2_instance already uses TagSpecifications when calling run_instances.  Since we're deprecating the original ec2 module (https://github.com/ansible-collections/amazon.aws/pull/424) I'm going to close this issue.
