### ISSUE TITLE
Bad API docs

### ISSUE THREAD

**Issue by mcandre** [ansible-collections/community.aws#582]
##### SUMMARY
The documentation omits many required fields for ec2_epi's, and doesn't document important things like region or domain, which are absolutely essential. These fields are even missing from the example code snippets.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

ec2_eip

**Comment by tremble** [comment]
Hi @mcandre,

Thanks for taking the time to open this report.

I see region:
https://docs.ansible.com/ansible/latest/collections/community/aws/ec2_eip_module.html#parameter-region

EIP's don't have a domain so I'm not sure which parameter you're referring to there.

If you're looking at the docs fragment in the module's python code itself, then it's expected that some parameters are missing: they're included in a separate fragment which is merged with the docs in the module
```
extends_documentation_fragment:
        - amazon.aws.aws
        - amazon.aws.ec2
```

Could you provide a link to the docs that are missing the required parameters please, and a little more detail about exactly which parameters you are unable to find in the docs.

**Comment by tremble** [comment]
With regards the missing credentials in the examples, the top of the examples says:
```
# Note: These examples do not set authentication details, see the AWS Guide for details.
```

The guide to which it refers: https://docs.ansible.com/ansible/latest/scenario_guides/guide_aws.html#authentication

**Comment by tremble** [comment]
I'm going to close this issue as there's currently nothing actionable in the report and the reporter hasn't responded in over 2 months.  If you're able to provide links to the "bad" docs the feel free to reopen the issue and provide the information requested.
