### ISSUE TITLE
Where are the lookups ?

### ISSUE THREAD

**Issue by rrey** [ansible-collections/community.aws#73]
##### SUMMARY

Ansible contained lookups for aws, like aws_secret : https://github.com/ansible/ansible/blob/stable-2.8/lib/ansible/plugins/lookup/aws_secret.py

Any reason not having them in the collection ?

##### ISSUE TYPE
- Bug Report

**Comment by briantist** [comment]
They are in the `amazon.aws` collection:
https://github.com/ansible-collections/amazon.aws/tree/master/plugins/lookup

**Comment by rrey** [comment]
Thanks @briantist !
