### ISSUE TITLE
aws_ssm  gov cloud error

### ISSUE THREAD

**Issue by mo1090** [ansible-collections/community.aws#828]
### Summary

I have been able to get the aws_ssm plugin working for AWS commercial, but when I tried to get it implemented in gov cloud I keep getting errors around the pre-signed url that is generated for the S3 bucket, a error for the "in_file_transport_command" for the bucket name, and a error for the "valid_bucket" name.  I have defined all the required variables as defined in the variable file, but I am at a loss on these errors.

### Issue Type

Bug Report

### Component Name

aws_ssm

### Ansible Version

```console (paste below)
$ ansible --version

```
2.11.6

### Collection Versions

```console (paste below)
$ ansible-galaxy collection list
```
aws_ssm

### AWS SDK versions

```console (paste below)
$ pip show boto boto3 botocore
```

### Configuration

```console (paste below)
$ ansible-config dump --only-changed

```

### OS / Environment

Target is Windows

### Steps to Reproduce

```yaml (paste below)

```
N/A

### Expected Results

Establish connection to Windows from RHEL, not happening

### Actual Results

```console (paste below)

```
N/A

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by phene** [comment]
Is this still an issue, @mo1090 ? Do you have any other details?

**Comment by phene** [comment]
I believe https://github.com/ansible-collections/community.aws/pull/1428 might fix this.

**Comment by mo1090** [comment]
It is no longer an issue.  Thanks for checking in

**Comment by phene** [comment]
@ansibullbot Close this issue.
