### ISSUE TITLE
DynamoDB support for TableClass

### ISSUE THREAD

**Issue by nick-zh** [ansible-collections/community.aws#829]
### Summary

It would be great to have support for table class for DynamoDB, depending on the use case, this can save cost
Possile values are:
```
TableClass: 'STANDARD'|'STANDARD_INFREQUENT_ACCESS
```

### Issue Type

Feature Idea

### Component Name

dynamodb

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by alinabuzachis** [comment]
@nick-zh thank you for this feature idea. Would you be willing to work on this and open and pull request?

**Comment by nick-zh** [comment]
I am quite busy on a new project, but once i find some time, i can try to add it :v:

**Comment by nick-zh** [comment]
Many thanks :heart:
