### ISSUE TITLE
OpenSearch, ElasticSearch module

### ISSUE THREAD

**Issue by sebastien-rosset** [ansible-collections/community.aws#858]
### Summary

It would be useful to have a `ec2_opensearch` module to deploy opensearch/elasticsearch clusters. Is it missing because nobody from the community submitted a PR? Or was it intentionally not added? Some other reason?

There is one module outside this repo (https://github.com/fiunchinho/ansible-aws-elasticsearch-module), but it hasn't been updated in the last 3 years.

### Issue Type

Feature Idea

### Component Name

opensearch

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by sebastien-rosset** [comment]
> I agree with @alinabuzachis, the new module would go into community.aws. It should be named `opensearch` rather than `ec2_opensearch` as this service does not use the EC2 API.

Thanks. So it will be `community.aws/plugins/modules/opensearch.py`, right? I see some modules are prefixed with aws, some don't.

**Comment by markuman** [comment]
>  Is it missing because nobody from the community submitted a PR? Or was it intentionally not added? Some other reason?  
>  I see some modules are prefixed with aws, some don't.

I would call it: "grown historically" :)

> Thanks. So it will be community.aws/plugins/modules/opensearch.py, right? 

right.
