### ISSUE TITLE
Question: How to support maintainers

### ISSUE THREAD

**Issue by nick-zh** [ansible-collections/community.aws#884]
### Summary

Is there a way to support the work of the current maintainers?
For example is a Github Sponsorship planned?
As my time is very limited atm and i cannot help out, i would still like to show my
appreciation for this project with a sponsorship or something similar :heart: 

Sry is not a feature request, but there was no matching category :sweat_smile: 

### Issue Type

Feature Idea

### Component Name

none

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by nick-zh** [comment]
@tremble @marknet15 if setting this up for the ansible collections org is not wanted or in spirit, consider setting it up on your personal profile (and encourage other contributors to do the same), i am sure there are some people out there that would like to show their appreciation with a small gesture for the support they are getting in this project :heart: 

Happy day :v:

**Comment by tremble** [comment]
@nick-zh,

Thanks for the appreciation that lies behind this "Issue".

While I'm not a member of Red Hat's engineering teams, Red Hat is my employer (I'm a part of Red Hat's IT department) and as such I wouldn't feel comfortable receiving much more than a "thank-you" message.  Similarly I don't feel comfortable commenting on what may or may not be wanted at the "Ansible collections org" level.

If @markuman, @marknet15 or any other maintainers wish to comment, they're most welcome to.

**Comment by nick-zh** [comment]
Then all I can say is: Thank you very much for all the effort that all of you are putting in. I highly appreciate it 💪 
Many thanks and have a great day!
