### ISSUE TITLE
Add 'tags' parameter to iam_managed_policy module

### ISSUE THREAD

**Issue by sebastien-rosset** [ansible-collections/community.aws#889]
### Summary

I am trying to assign tags to iam policies that are created using the `iam_managed_policy` module. This module currently does not support tags.

### Issue Type

Feature Idea

### Component Name

iam_managed_policy

### Additional Information

```yaml (paste below)

```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by markuman** [comment]
Duplicated: https://github.com/ansible-collections/community.aws/issues/566
